version: "2"
services:
  zookeeper:
    image: zookeeper:3.4.10
    network_mode: host
  mesos_master:
    image:  mesosphere/mesos-master:1.7.0
    network_mode: host
    environment:
      MESOS_ZK: "zk://localhost:2181/mesos"
      MESOS_WORK_DIR: "/var/tmp/mesos"
      MESOS_LOG_DIR: "/var/log/mesos"
      MESOS_IP: 127.0.0.1
      MESOS_HOSTNAME: "localhost"
    depends_on:
      - zookeeper
  mesos_agent:
    image: mesosphere/mesos-slave:1.7.0
    #  build:
    #    context: ./api/v1/cmd/example-executor
    #    dockerfile: Dockerfile
    network_mode: host
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.pid:/var/run/docker.pid
      - /cgroup:/cgroup
      - /sys:/sys
      - /proc:/mnt/proc
    ports:
      - "2345:2345"
      - "5051:5051"
    environment:
      MESOS_MASTER: "zk://localhost:2181/mesos"
      MESOS_PORT: "5051"
      MESOS_WORK_DIR: "/var/tmp/mesos"
      MESOS_LOG_DIR: "/var/log/mesos"
      MESOS_SWITCH_USER: "false"
      MESOS_CONTAINERIZERS: "docker,mesos"
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
    depends_on:
      - zookeeper
      - mesos_master